In [1]:
import numpy as np


In [2]:
B = np.array([[3,-1],[-2,3]])
C = np.array([0.2,0.8])
c1=np.array([[0.2],[0.8]])

In [3]:
B.reshape((2,2))
C.reshape((2,1))

array([[0.2],
       [0.8]])

In [4]:
B*C

array([[ 0.6, -0.8],
       [-0.4,  2.4]])

In [5]:
X = 0.35
np.dot(B,C)

array([-0.2,  2. ])

In [6]:
y = np.matmul(B,C)

In [7]:
y

array([-0.2,  2. ])

In [8]:
a = np.array([[0.75,0.25]])
a.shape

(1, 2)

In [9]:
i = np.matmul(a,y)

In [10]:
i.shape

(1,)

In [11]:

m = np.matmul(B,C)
ans=(.35-2)/(-.2-2)
print(ans)

#which will deduce A0 to as below

#a0 = (X-z)/(y-z)

0.7499999999999999


X=A*B*C
X=A*y
.35 = (a0,1-a0)*[-0.2,2]
y=B*C matrix mult
A1 = 1-A0
find A
given the rest
a0*-.2 + (1-a0)*2 = .35
a0 = .75
a1=1-.75 = .25
A=[a0,a1]

In [16]:
load = np.loadtxt("datatest2.txt")

In [17]:
print(load)

[[ 3.  2.  5.  5.  5.]
 [ 7.  5.  3.  0.  0.]
 [ 9.  0. 10. 11. 11.]
 [ 5.  0.  0.  0.  0.]
 [ 6.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.]]


In [21]:
gen = np.genfromtxt("datatest.txt", delimiter=',')

In [22]:
print(gen)

[[ 5.  3.  4.  7.  2. 57. 34. 23.  8.  6. 43.  2.]
 [ 5. 54.  7.  9.  3.  4.  7.  3.  1.  2.  0. 98.]
 [ 5. 64.  5.  4.  2.  6.  3.  4.  8.  6.  3.  2.]]


In [25]:
gen2 = np.genfromtxt("datatest2.txt", delimiter=' ')

In [26]:
gen2

array([[ 3.,  2.,  5.,  5.,  5.],
       [ 7.,  5.,  3.,  0.,  0.],
       [ 9.,  0., 10., 11., 11.],
       [ 5.,  0.,  0.,  0.,  0.],
       [ 6.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.]])

In [27]:
gen3 = np.genfromtxt("datatest3.txt", delimiter='%')

In [28]:
print(gen3)

[[5. 3. 4.]
 [2. 3. 7.]]


In [34]:
arr1 = [1, 2, 3]
arr2 = ['a', 'b', 'c']
result  = zip(arr1, arr2)
settedresult = set(result)

In [35]:
print(settedresult)

{(1, 'a'), (3, 'c'), (2, 'b')}


In [36]:
a1=np.array([1,2,3,4,5])
b1=np.array([2,4,6,8,10])
result2  = zip(a1, b1)
list_of_ab= list(result2)
print(list_of_ab)

[(1, 2), (2, 4), (3, 6), (4, 8), (5, 10)]


In [37]:
c1=np.array(result2)

In [38]:
print(c1)

In [41]:
a2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
result3 = zip(a2[0], a2[1])
list_of_ab2= list(result3)
print(list_of_ab2)

[(1, 2), (2, 3), (3, 4), (4, 5), (5, 6)]


In [43]:
for y in list_of_ab2:
    print(y)

(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)


In [55]:
if 1 > 2:
    print("Five is greater than two!")
else:
    print("wrong")

wrong


In [47]:
""" 
This is a comment
written in
more than just one line
"""

'\nThis is a comment\nwritten in\nmore than just one line\n'

In [52]:
a = 5.1

x = str(a)    # x will be '3'
y = int(a)    # y will be 3
z = float(a)  # z will be 3.0

print(x,y,z)
print(type(x),type(y),type(z))

5.1 5 5.1
<class 'str'> <class 'int'> <class 'float'>


In [51]:
x = "awesome"

def function():
    global x
    x = "fantastic"
    print("Python is " + x)

function()

print("Python is " + x)

Python is fantastic
Python is fantastic


In [54]:
def myFunction() :
    return False

if myFunction():
    print("YES!")
else:
    print("NO!")


NO!
