In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
a1.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.nbytes

12

In [11]:
a.size

3

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a[1, 5]

13

In [14]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
a[:, 2]

array([ 3, 10])

In [16]:
a[0, 1:-1:2]

array([2, 4, 6])

In [17]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
b[0,1,1]

4

In [22]:
b[:,1,:] = [[9,9],[8,8]]

In [23]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [24]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [26]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [27]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [159]:
r=np.random.rand(4,2)
r=r*100
print(r)

[[23.37097353 75.65111617]
 [60.56844636  2.77001572]
 [50.4804266  84.19183459]
 [95.7673497  20.99553762]]


In [160]:
np.ceil(r)

array([[24., 76.],
       [61.,  3.],
       [51., 85.],
       [96., 21.]])

In [41]:
np.random.randint(-4,8, size=(10,10))

array([[-4, -1, -3,  5,  4,  5, -2,  1,  7,  6],
       [-1, -1, -3, -3,  7,  1, -1,  2,  7,  7],
       [-3,  3,  7,  5, -2, -3,  1,  7,  4,  0],
       [ 1,  2,  5,  2,  5,  6,  4,  5, -4,  2],
       [-3, -3,  0, -1, -4,  5, -4, -3, -4, -4],
       [ 5, -4, -1, -4, -1,  3,  3,  5, -1,  0],
       [ 1,  4,  4,  4,  4,  1,  1, -4,  7, -4],
       [ 6, -3, -1,  4,  7,  4,  4,  5, -3, -1],
       [ 1,  7,  3,  3,  6,  5,  2,  1, -3, -1],
       [ 4, -4,  0,  0,  1,  2,  6, -1,  0, -1]])

In [42]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a + 2

array([3, 4, 5, 6])

In [49]:
a - 2

array([-1,  0,  1,  2])

In [50]:
a * 2

array([2, 4, 6, 8])

In [51]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [52]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [53]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [54]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [56]:
##https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [57]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [58]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [59]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [60]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.min(stats)

1

In [62]:
np.max(stats, axis=1)

array([3, 6])

In [63]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [66]:
before = np.array([[1,2,3,5,6,7]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 5 6 7]]
[[1 2 3]
 [5 6 7]]


In [67]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [70]:
filedata = np.genfromtxt('datatest.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[ 5  3  4  7  2 57 34 23  8  6 43  2]
 [ 5 54  7  9  3  4  7  3  1  2  0 98]
 [ 5 64  5  4  2  6  3  4  8  6  3  2]]


In [71]:
filedata >50

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False],
       [False,  True, False, False, False, False, False, False, False,
        False, False,  True],
       [False,  True, False, False, False, False, False, False, False,
        False, False, False]])

In [72]:
filedata[filedata > 50]

array([57, 54, 98, 64])

In [73]:
filedata[filedata > 10]

array([57, 34, 23, 43, 54, 98, 64])

In [74]:
a = np.array([1,2,3,4,5,6,7,8,9,0,7,6,4,2,4])
a[[1,4,8]]

array([2, 5, 9])

In [85]:
 a1=np.arange(1,31)
print(a1)

a1sized=a1.reshape(6,5)
print(a1sized)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [83]:
a1sized[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [103]:
a1sized[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [87]:
a1sized[[0,1,2,3]]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
a1sized[:,[1,2,3,4]]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25],
       [27, 28, 29, 30]])

In [92]:
a1sized[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [98]:
a1sized[[0,4,5],2:4]

array([[ 3,  4],
       [23, 24],
       [28, 29]])

In [104]:
a1sized[4:6,0:2]

array([[21, 22],
       [26, 27]])

In [106]:
a1sized[0,:]

array([1, 2, 3, 4, 5])

In [107]:
a1sized[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [108]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [110]:
a=np.array([[1,2],[5,1]])
b=np.array([[4,2],[1,3]])

In [111]:
print(a)
print(b)

[[1 2]
 [5 1]]
[[4 2]
 [1 3]]


In [113]:
1*4+2*1

6

In [114]:
1*2+2*3

8

In [115]:
5*4+1*1

21

In [116]:
5*2+1*3

13

In [118]:
answer=np.array([[6,8],[21,13]])
print(answer)

[[ 6  8]
 [21 13]]


In [119]:
np.matmul(a,b)

array([[ 6,  8],
       [21, 13]])

In [122]:
i=np.identity(2)
print(i)

[[1. 0.]
 [0. 1.]]


In [123]:
np.matmul(a,i)

array([[1., 2.],
       [5., 1.]])

In [124]:
np.matmul(b,i)

array([[4., 2.],
       [1., 3.]])

In [125]:
np.matmul(b,a)

array([[14, 10],
       [16,  5]])

In [127]:
at=np.transpose(a)
print(a)
print(at)

[[1 2]
 [5 1]]
[[1 5]
 [2 1]]


In [138]:
bt=np.transpose(b)
print(b)
print(bt)

[[4 2]
 [1 3]]
[[4 1]
 [2 3]]


In [143]:
c=np.array([[1,2,3,4,5,6,7,8]])
ct=np.transpose(c)
print(c)
print(ct)

[[1 2 3 4 5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [146]:
#numpy.indices will create a set of arrays (stacked as a one-higher dimensioned array), 
#one per dimension with each representing variation in that dimension:
d=np.indices((2,2))

In [147]:
print(d)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


In [148]:
# numpy.block
np.block([[a, b],
          [i, at]])

array([[1., 2., 4., 2.],
       [5., 1., 1., 3.],
       [1., 0., 1., 5.],
       [0., 1., 2., 1.]])

In [150]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [152]:
a*b+10


array([[14, 14],
       [15, 13]])

In [165]:
np.linspace(0, 100, num=11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])